version: '2'

services:
  # Database
  db:
    image: mysql:5.7
    container_name: mysql_db
    volumes:
      - /root/mysql_volume:/var/lib/mysql
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: password12
     #MYSQL_DATABASE: my_database
     #MYSQL_USER: user1
     #MYSQL_PASSWORD: passw0rd
  # phpmyadmin
  phpmyadmin:
    #depends_on:
     # - db
     links:
      - db:db
     image: phpmyadmin/phpmyadmin
     container_name: phpAdm
     restart: always
     ports:
      - '8080:80' #Redirect 80 port to 8080
     environment:
      MYSQL_ROOT_PASSWORD: password12 #Same password to mysql root user
      PMA_PORT: 3306
